apiVersion: v1
kind: Service
metadata: 
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    name: api-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    metadata:
      labels:
        name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 117905818048.dkr.ecr.us-west-2.amazonaws.com/api/gateway:1.2 
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey
