kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-09fb75e6527340959 
    fsType: ext4
