apiVersion: v1
kind: Service
metadata: 
  name: jenkins
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 50000
      name: jenkins-master
  selector:
    name: jenkins
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkins
          image: jenkins
          args: ["jenkins", "jenkins", "1000", "1000"]
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-vol
          awsElasticBlockStore:
            volumeID: vol-037946f4eac248204
            fsType: ext4
